package com.ericlara.flightBooker.Models;

import java.util.List;
//HARDCODED AIRPORT DATA REPOSITORY
//SOURCE: https://en.wikipedia.org/wiki/List_of_airports_in_the_United_States

public class AirportData {
    private AirportData(){}
    public static List<Airport> usAirports = List.of(
        Airport.builder().name("Birmingham–Shuttlesworth International Airport").city("Birmingham").state("Alabama").iataId("BHM").build(),
        Airport.builder().name("Dothan Regional Airport").city("Dothan").state("Alabama").iataId("DHN").build(),
        Airport.builder().name("Huntsville International Airport (Carl T. Jones Field)").city("Huntsville").state("Alabama").iataId("HSV").build(),
        Airport.builder().name("Mobile Regional Airport").city("Mobile").state("Alabama").iataId("MOB").build(),
        Airport.builder().name("Montgomery Regional Airport (Dannelly Field)").city("Montgomery").state("Alabama").iataId("MGM").build(),
        Airport.builder().name("Merrill Field").city("Anchorage").state("Alaska").iataId("MRI").build(),
        Airport.builder().name("Ted Stevens Anchorage International Airport").city("Anchorage").state("Alaska").iataId("ANC").build(),
        Airport.builder().name("Bethel Airport (also see Bethel Seaplane Base)").city("Bethel").state("Alaska").iataId("BET").build(),
        Airport.builder().name("Merle K. (Mudhole) Smith Airport").city("Cordova").state("Alaska").iataId("CDV").build(),
        Airport.builder().name("Deadhorse Airport (Prudhoe Bay Airport)").city("Deadhorse").state("Alaska").iataId("SCC").build(),
        Airport.builder().name("Dillingham Airport").city("Dillingham").state("Alaska").iataId("DLG").build(),
        Airport.builder().name("Fairbanks International Airport").city("Fairbanks").state("Alaska").iataId("FAI").build(),
        Airport.builder().name("Gustavus Airport").city("Gustavus").state("Alaska").iataId("GST").build(),
        Airport.builder().name("Homer Airport").city("Homer").state("Alaska").iataId("HOM").build(),
        Airport.builder().name("Juneau International Airport").city("Juneau").state("Alaska").iataId("JNU").build(),
        Airport.builder().name("Kenai Municipal Airport").city("Kenai").state("Alaska").iataId("ENA").build(),
        Airport.builder().name("Ketchikan International Airport").city("Ketchikan").state("Alaska").iataId("KTN").build(),
        Airport.builder().name("King Salmon Airport").city("King Salmon").state("Alaska").iataId("AKN").build(),
        Airport.builder().name("Klawock Airport (also see Klawock Seaplane Base)").city("Klawock").state("Alaska").iataId("AKW").build(),
        Airport.builder().name("Kodiak Airport (Benny Benson State Airport)").city("Kodiak").state("Alaska").iataId("ADQ").build(),
        Airport.builder().name("Ralph Wien Memorial Airport").city("Kotzebue").state("Alaska").iataId("OTZ").build(),
        Airport.builder().name("Nome Airport").city("Nome").state("Alaska").iataId("OME").build(),
        Airport.builder().name("Petersburg James A. Johnson Airport").city("Petersburg").state("Alaska").iataId("PSG").build(),
        Airport.builder().name("Sitka Rocky Gutierrez Airport").city("Sitka").state("Alaska").iataId("SIT").build(),
        Airport.builder().name("Unalaska Airport (Tom Madsen/Dutch Harbor Airport)").city("Unalaska").state("Alaska").iataId("DUT").build(),
        Airport.builder().name("Wiley Post–Will Rogers Memorial Airport").city("Utqiaġvik (Barrow)").state("Alaska").iataId("BRW").build(),
        Airport.builder().name("Wrangell Airport (also see Wrangell Seaplane Base)").city("Wrangell").state("Alaska").iataId("WRG").build(),
        Airport.builder().name("Yakutat Airport (also see Yakutat Seaplane Base)").city("Yakutat").state("Alaska").iataId("YAK").build(),
        Airport.builder().name("Flagstaff Pulliam Airport").city("Flagstaff").state("Arizona").iataId("FLG").build(),
        Airport.builder().name("Phoenix–Mesa Gateway Airport (formerly Williams AFB)").city("Mesa").state("Arizona").iataId("IWA").build(),
        Airport.builder().name("Page Municipal Airport").city("Page").state("Arizona").iataId("PGA").build(),
        Airport.builder().name("Phoenix Sky Harbor International Airport").city("Phoenix").state("Arizona").iataId("PHX").build(),
        Airport.builder().name("Prescott Municipal Airport (Ernest A. Love Field)").city("Prescott").state("Arizona").iataId("PRC").build(),
        Airport.builder().name("Tucson International Airport").city("Tucson").state("Arizona").iataId("TUS").build(),
        Airport.builder().name("Yuma International Airport / MCAS Yuma").city("Yuma").state("Arizona").iataId("NYL").build(),
        Airport.builder().name("Northwest Arkansas National Airport").city("Fayetteville").state("Arkansas").iataId("XNA").build(),
        Airport.builder().name("Fort Smith Regional Airport").city("Fort Smith").state("Arkansas").iataId("FSM").build(),
        Airport.builder().name("Bill and Hillary Clinton National Airport (Adams Field) (was Little Rock National)").city("Little Rock").state("Arkansas").iataId("LIT").build(),
        Airport.builder().name("Texarkana Regional Airport (Webb Field)").city("Texarkana").state("Arkansas").iataId("TXK").build(),
        Airport.builder().name("California Redwood Coast–Humboldt County Airport").city("Arcata/Eureka").state("California").iataId("ACV").build(),
        Airport.builder().name("Meadows Field").city("Bakersfield").state("California").iataId("BFL").build(),
        Airport.builder().name("Hollywood Burbank Airport").city("Burbank").state("California").iataId("BUR").build(),
        Airport.builder().name("Fresno Yosemite International Airport").city("Fresno").state("California").iataId("FAT").build(),
        Airport.builder().name("Long Beach Airport (Daugherty Field)").city("Long Beach").state("California").iataId("LGB").build(),
        Airport.builder().name("Los Angeles International Airport").city("Los Angeles").state("California").iataId("LAX").build(),
        Airport.builder().name("Monterey Regional Airport").city("Monterey").state("California").iataId("MRY").build(),
        Airport.builder().name("Oakland International Airport").city("Oakland").state("California").iataId("OAK").build(),
        Airport.builder().name("Ontario International Airport").city("Ontario").state("California").iataId("ONT").build(),
        Airport.builder().name("John Wayne Airport").city("Orange County").state("California").iataId("SNA").build(),
        Airport.builder().name("Palm Springs International Airport").city("Palm Springs").state("California").iataId("PSP").build(),
        Airport.builder().name("Redding Municipal Airport").city("Redding").state("California").iataId("RDD").build(),
        Airport.builder().name("Sacramento International Airport").city("Sacramento").state("California").iataId("SMF").build(),
        Airport.builder().name("San Diego International Airport (Lindbergh Field)").city("San Diego").state("California").iataId("SAN").build(),
        Airport.builder().name("San Francisco International Airport").city("San Francisco").state("California").iataId("SFO").build(),
        Airport.builder().name("San José Mineta International Airport").city("San Jose").state("California").iataId("SJC").build(),
        Airport.builder().name("San Luis Obispo County Regional Airport (McChesney Field)").city("San Luis Obispo").state("California").iataId("SBP").build(),
        Airport.builder().name("Santa Barbara Municipal Airport (Santa Barbara Airport)").city("Santa Barbara").state("California").iataId("SBA").build(),
        Airport.builder().name("Santa Maria Public Airport (Capt G. Allan Hancock Field)").city("Santa Maria").state("California").iataId("SMX").build(),
        Airport.builder().name("Charles M. Schulz–Sonoma County Airport").city("Santa Rosa").state("California").iataId("STS").build(),
        Airport.builder().name("Stockton Metropolitan Airport").city("Stockton").state("California").iataId("SCK").build(),
        Airport.builder().name("San Luis Valley Regional Airport (Bergman Field)").city("Alamosa").state("Colorado").iataId("ALS").build(),
        Airport.builder().name("Aspen/Pitkin County Airport (Sardy Field)").city("Aspen").state("Colorado").iataId("ASE").build(),
        Airport.builder().name("City of Colorado Springs Municipal Airport").city("Colorado Springs").state("Colorado").iataId("COS").build(),
        Airport.builder().name("Denver International Airport").city("Denver").state("Colorado").iataId("DEN").build(),
        Airport.builder().name("Durango–La Plata County Airport").city("Durango").state("Colorado").iataId("DRO").build(),
        Airport.builder().name("Eagle County Regional Airport").city("Eagle/Vail").state("Colorado").iataId("EGE").build(),
        Airport.builder().name("Grand Junction Regional Airport (Walker Field)").city("Grand Junction").state("Colorado").iataId("GJT").build(),
        Airport.builder().name("Gunnison–Crested Butte Regional Airport").city("Gunnison").state("Colorado").iataId("GUC").build(),
        Airport.builder().name("Yampa Valley Airport (Yampa Valley Regional)").city("Hayden").state("Colorado").iataId("HDN").build(),
        Airport.builder().name("Montrose Regional Airport").city("Montrose").state("Colorado").iataId("MTJ").build(),
        Airport.builder().name("Bradley International Airport").city("Hartford").state("Connecticut").iataId("BDL").build(),
        Airport.builder().name("Tweed-New Haven Airport").city("New Haven").state("Connecticut").iataId("HVN").build(),
        Airport.builder().name("Wilmington Airport").city("Wilmington").state("Delaware").iataId("ILG").build(),
        Airport.builder().name("Daytona Beach International Airport").city("Daytona Beach").state("Florida").iataId("DAB").build(),
        Airport.builder().name("Fort Lauderdale–Hollywood International Airport").city("Fort Lauderdale").state("Florida").iataId("FLL").build(),
        Airport.builder().name("Southwest Florida International Airport").city("Fort Myers").state("Florida").iataId("RSW").build(),
        Airport.builder().name("Destin–Fort Walton Beach Airport / Eglin Air Force Base").city("Fort Walton Beach").state("Florida").iataId("VPS").build(),
        Airport.builder().name("Gainesville Regional Airport").city("Gainesville").state("Florida").iataId("GNV").build(),
        Airport.builder().name("Jacksonville International Airport").city("Jacksonville").state("Florida").iataId("JAX").build(),
        Airport.builder().name("Key West International Airport").city("Key West").state("Florida").iataId("EYW").build(),
        Airport.builder().name("Melbourne Orlando International Airport").city("Melbourne").state("Florida").iataId("MLB").build(),
        Airport.builder().name("Miami International Airport").city("Miami").state("Florida").iataId("MIA").build(),
        Airport.builder().name("Orlando International Airport").city("Orlando").state("Florida").iataId("MCO").build(),
        Airport.builder().name("Northwest Florida Beaches International Airport").city("Panama City").state("Florida").iataId("ECP").build(),
        Airport.builder().name("Pensacola International Airport").city("Pensacola").state("Florida").iataId("PNS").build(),
        Airport.builder().name("Punta Gorda Airport").city("Punta Gorda").state("Florida").iataId("PGD").build(),
        Airport.builder().name("Orlando Sanford International Airport").city("Sanford").state("Florida").iataId("SFB").build(),
        Airport.builder().name("Sarasota–Bradenton International Airport").city("Sarasota").state("Florida").iataId("SRQ").build(),
        Airport.builder().name("St. Pete–Clearwater International Airport").city("St. Petersburg").state("Florida").iataId("PIE").build(),
        Airport.builder().name("Tallahassee International Airport").city("Tallahassee").state("Florida").iataId("TLH").build(),
        Airport.builder().name("Tampa International Airport").city("Tampa").state("Florida").iataId("TPA").build(),
        Airport.builder().name("Palm Beach International Airport").city("West Palm Beach").state("Florida").iataId("PBI").build(),
        Airport.builder().name("Southwest Georgia Regional Airport").city("Albany").state("Georgia").iataId("ABY").build(),
        Airport.builder().name("Hartsfield–Jackson Atlanta International Airport").city("Atlanta").state("Georgia").iataId("ATL").build(),
        Airport.builder().name("Augusta Regional Airport (Bush Field)").city("Augusta").state("Georgia").iataId("AGS").build(),
        Airport.builder().name("Brunswick Golden Isles Airport").city("Brunswick").state("Georgia").iataId("BQK").build(),
        Airport.builder().name("Columbus Airport").city("Columbus").state("Georgia").iataId("CSG").build(),
        Airport.builder().name("Middle Georgia Regional Airport").city("Macon").state("Georgia").iataId("MCN").build(),
        Airport.builder().name("Savannah/Hilton Head International Airport").city("Savannah").state("Georgia").iataId("SAV").build(),
        Airport.builder().name("Valdosta Regional Airport").city("Valdosta").state("Georgia").iataId("VLD").build(),
        Airport.builder().name("Hilo International Airport").city("Hilo, Hawaii").state("Hawaii").iataId("ITO").build(),
        Airport.builder().name("Daniel K. Inouye International Airport").city("Honolulu, Oahu").state("Hawaii").iataId("HNL").build(),
        Airport.builder().name("Kahului Airport").city("Kahului, Maui").state("Hawaii").iataId("OGG").build(),
        Airport.builder().name("Ellison Onizuka Kona International Airport at Keahole").city("Kailua-Kona, Hawaii").state("Hawaii").iataId("KOA").build(),
        Airport.builder().name("Molokai Airport (Hoolehua Airport)").city("Kaunakakai, Molokai").state("Hawaii").iataId("MKK").build(),
        Airport.builder().name("Lanai Airport").city("Lanai City, Lanai").state("Hawaii").iataId("LNY").build(),
        Airport.builder().name("Lihue Airport").city("Lihue, Kauai").state("Hawaii").iataId("LIH").build(),
        Airport.builder().name("Boise Airport (Boise Air Terminal) (Gowen Field)").city("Boise").state("Idaho").iataId("BOI").build(),
        Airport.builder().name("Friedman Memorial Airport").city("Hailey / Sun Valley").state("Idaho").iataId("SUN").build(),
        Airport.builder().name("Idaho Falls Regional Airport (Fanning Field)").city("Idaho Falls").state("Idaho").iataId("IDA").build(),
        Airport.builder().name("Lewiston–Nez Perce County Airport").city("Lewiston").state("Idaho").iataId("LWS").build(),
        Airport.builder().name("Pocatello Regional Airport").city("Pocatello").state("Idaho").iataId("PIH").build(),
        Airport.builder().name("Magic Valley Regional Airport (Joslin Field)").city("Twin Falls").state("Idaho").iataId("TWF").build(),
        Airport.builder().name("MidAmerica St. Louis Airport / Scott Air Force Base").city("Belleville").state("Illinois").iataId("BLV").build(),
        Airport.builder().name("Central Illinois Regional Airport at Bloomington-Normal").city("Bloomington / Normal").state("Illinois").iataId("BMI").build(),
        Airport.builder().name("University of Illinois - Willard Airport").city("Champaign / Urbana / Savoy").state("Illinois").iataId("CMI").build(),
        Airport.builder().name("Chicago Midway International Airport").city("Chicago").state("Illinois").iataId("MDW").build(),
        Airport.builder().name("Chicago O'Hare International Airport").city("Chicago").state("Illinois").iataId("ORD").build(),
        Airport.builder().name("Veterans Airport of Southern Illinois (Williamson County Regional Airport)").city("Marion").state("Illinois").iataId("MWA").build(),
        Airport.builder().name("Quad City International Airport").city("Moline").state("Illinois").iataId("MLI").build(),
        Airport.builder().name("General Downing-Peoria International Airport").city("Peoria").state("Illinois").iataId("PIA").build(),
        Airport.builder().name("Chicago Rockford International Airport (was Northwest Chicagoland Regional Airport at Rockford)").city("Rockford").state("Illinois").iataId("RFD").build(),
        Airport.builder().name("Abraham Lincoln Capital Airport").city("Springfield").state("Illinois").iataId("SPI").build(),
        Airport.builder().name("Evansville Regional Airport").city("Evansville").state("Indiana").iataId("EVV").build(),
        Airport.builder().name("Fort Wayne International Airport").city("Fort Wayne").state("Indiana").iataId("FWA").build(),
        Airport.builder().name("Indianapolis International Airport").city("Indianapolis").state("Indiana").iataId("IND").build(),
        Airport.builder().name("South Bend International Airport").city("South Bend").state("Indiana").iataId("SBN").build(),
        Airport.builder().name("Eastern Iowa Airport").city("Cedar Rapids").state("Iowa").iataId("CID").build(),
        Airport.builder().name("Des Moines International Airport").city("Des Moines").state("Iowa").iataId("DSM").build(),
        Airport.builder().name("Dubuque Regional Airport").city("Dubuque").state("Iowa").iataId("DBQ").build(),
        Airport.builder().name("Sioux Gateway Airport (Brig. General Bud Day Field)").city("Sioux City").state("Iowa").iataId("SUX").build(),
        Airport.builder().name("Waterloo Regional Airport").city("Waterloo").state("Iowa").iataId("ALO").build(),
        Airport.builder().name("Garden City Regional Airport").city("Garden City").state("Kansas").iataId("GCK").build(),
        Airport.builder().name("Hays Regional Airport").city("Hays").state("Kansas").iataId("HYS").build(),
        Airport.builder().name("Manhattan Regional Airport").city("Manhattan").state("Kansas").iataId("MHK").build(),
        Airport.builder().name("Salina Regional Airport").city("Salina").state("Kansas").iataId("SLN").build(),
        Airport.builder().name("Wichita Dwight D. Eisenhower National Airport (was Wichita Mid-Continent Airport)").city("Wichita").state("Kansas").iataId("ICT").build(),
        Airport.builder().name("Cincinnati/Northern Kentucky International Airport").city("Cincinnati/Covington").state("Kentucky").iataId("CVG").build(),
        Airport.builder().name("Blue Grass Airport").city("Lexington").state("Kentucky").iataId("LEX").build(),
        Airport.builder().name("Louisville International Airport (Standiford Field)").city("Louisville").state("Kentucky").iataId("SDF").build(),
        Airport.builder().name("Owensboro–Daviess County Regional Airport").city("Owensboro").state("Kentucky").iataId("OWB").build(),
        Airport.builder().name("Barkley Regional Airport").city("Paducah").state("Kentucky").iataId("PAH").build(),
        Airport.builder().name("Alexandria International Airport").city("Alexandria").state("Louisiana").iataId("AEX").build(),
        Airport.builder().name("Baton Rouge Metropolitan Airport (Ryan Field)").city("Baton Rouge").state("Louisiana").iataId("BTR").build(),
        Airport.builder().name("Lafayette Regional Airport (Paul Fournet Field)").city("Lafayette").state("Louisiana").iataId("LFT").build(),
        Airport.builder().name("Lake Charles Regional Airport").city("Lake Charles").state("Louisiana").iataId("LCH").build(),
        Airport.builder().name("Monroe Regional Airport").city("Monroe").state("Louisiana").iataId("MLU").build(),
        Airport.builder().name("Louis Armstrong New Orleans International Airport").city("New Orleans").state("Louisiana").iataId("MSY").build(),
        Airport.builder().name("Shreveport Regional Airport").city("Shreveport").state("Louisiana").iataId("SHV").build(),
        Airport.builder().name("Bangor International Airport").city("Bangor").state("Maine").iataId("BGR").build(),
        Airport.builder().name("Portland International Jetport").city("Portland").state("Maine").iataId("PWM").build(),
        Airport.builder().name("Presque Isle International Airport").city("Presque Isle").state("Maine").iataId("PQI").build(),
        Airport.builder().name("Knox County Regional Airport").city("Rockland").state("Maine").iataId("RKD").build(),
        Airport.builder().name("Baltimore/Washington International Airport").city("Baltimore").state("Maryland").iataId("BWI").build(),
        Airport.builder().name("Hagerstown Regional Airport (Richard A. Henson Field)").city("Hagerstown").state("Maryland").iataId("HGR").build(),
        Airport.builder().name("Salisbury–Ocean City–Wicomico Regional Airport").city("Salisbury").state("Maryland").iataId("SBY").build(),
        Airport.builder().name("Gen. Edward Lawrence Logan International Airport").city("Boston").state("Massachusetts").iataId("BOS").build(),
        Airport.builder().name("Cape Cod Gateway Airport (Boardman/Polando Field)").city("Hyannis").state("Massachusetts").iataId("HYA").build(),
        Airport.builder().name("Nantucket Memorial Airport").city("Nantucket").state("Massachusetts").iataId("ACK").build(),
        Airport.builder().name("Martha's Vineyard Airport").city("Vineyard Haven").state("Massachusetts").iataId("MVY").build(),
        Airport.builder().name("Worcester Regional Airport").city("Worcester").state("Massachusetts").iataId("ORH").build(),
        Airport.builder().name("Alpena County Regional Airport").city("Alpena").state("Michigan").iataId("APN").build(),
        Airport.builder().name("Detroit Metro Wayne County Airport").city("Detroit").state("Michigan").iataId("DTW").build(),
        Airport.builder().name("Delta County Airport").city("Escanaba").state("Michigan").iataId("ESC").build(),
        Airport.builder().name("Bishop International Airport").city("Flint").state("Michigan").iataId("FNT").build(),
        Airport.builder().name("Gerald R. Ford International Airport").city("Grand Rapids").state("Michigan").iataId("GRR").build(),
        Airport.builder().name("Houghton County Memorial Airport").city("Hancock").state("Michigan").iataId("CMX").build(),
        Airport.builder().name("Ford Airport").city("Iron Mountain").state("Michigan").iataId("IMT").build(),
        Airport.builder().name("Kalamazoo/Battle Creek International Airport").city("Kalamazoo").state("Michigan").iataId("AZO").build(),
        Airport.builder().name("Capital Region International Airport (was Lansing Capital City)").city("Lansing").state("Michigan").iataId("LAN").build(),
        Airport.builder().name("Sawyer International Airport").city("Marquette").state("Michigan").iataId("SAW").build(),
        Airport.builder().name("Muskegon County Airport").city("Muskegon").state("Michigan").iataId("MKG").build(),
        Airport.builder().name("Pellston Regional/Emmet County Airport").city("Pellston").state("Michigan").iataId("PLN").build(),
        Airport.builder().name("MBS International Airport").city("Saginaw").state("Michigan").iataId("MBS").build(),
        Airport.builder().name("Chippewa County International Airport").city("Sault Ste. Marie").state("Michigan").iataId("CIU").build(),
        Airport.builder().name("Cherry Capital Airport (was Cherry County Airpark)").city("Traverse City").state("Michigan").iataId("TVC").build(),
        Airport.builder().name("Bemidji Regional Airport").city("Bemidji").state("Minnesota").iataId("BJI").build(),
        Airport.builder().name("Brainerd Lakes Regional Airport").city("Brainerd").state("Minnesota").iataId("BRD").build(),
        Airport.builder().name("Duluth International Airport").city("Duluth").state("Minnesota").iataId("DLH").build(),
        Airport.builder().name("Range Regional Airport (was Chisholm–Hibbing Airport)").city("Hibbing").state("Minnesota").iataId("HIB").build(),
        Airport.builder().name("Minneapolis–St. Paul International/Wold-Chamberlain Airport").city("Minneapolis-St. Paul").state("Minnesota").iataId("MSP").build(),
        Airport.builder().name("Rochester International Airport").city("Rochester").state("Minnesota").iataId("RST").build(),
        Airport.builder().name("St. Cloud Regional Airport").city("St. Cloud").state("Minnesota").iataId("STC").build(),
        Airport.builder().name("Golden Triangle Regional Airport").city("Columbus").state("Mississippi").iataId("GTR").build(),
        Airport.builder().name("Gulfport–Biloxi International Airport").city("Gulfport / Biloxi").state("Mississippi").iataId("GPT").build(),
        Airport.builder().name("Hattiesburg–Laurel Regional Airport").city("Hattiesburg / Laurel").state("Mississippi").iataId("PIB").build(),
        Airport.builder().name("Jackson–Medgar Wiley Evers International Airport").city("Jackson").state("Mississippi").iataId("JAN").build(),
        Airport.builder().name("Key Field").city("Meridian").state("Mississippi").iataId("MEI").build(),
        Airport.builder().name("Tupelo Regional Airport (C.D. Lemons Field)").city("Tupelo").state("Mississippi").iataId("TUP").build(),
        Airport.builder().name("Branson Airport").city("Branson").state("Missouri").iataId("BBG").build(),
        Airport.builder().name("Columbia Regional Airport").city("Columbia").state("Missouri").iataId("COU").build(),
        Airport.builder().name("Waynesville-St. Robert Regional Airport (Forney Field)").city("Fort Leonard Wood / Waynesville").state("Missouri").iataId("TBN").build(),
        Airport.builder().name("Joplin Regional Airport").city("Joplin").state("Missouri").iataId("JLN").build(),
        Airport.builder().name("Kansas City International Airport (was Mid-Continent International)").city("Kansas City").state("Missouri").iataId("MCI").build(),
        Airport.builder().name("St. Louis Lambert International Airport").city("St. Louis").state("Missouri").iataId("STL").build(),
        Airport.builder().name("Springfield–Branson National Airport").city("Springfield").state("Missouri").iataId("SGF").build(),
        Airport.builder().name("Billings Logan International Airport").city("Billings").state("Montana").iataId("BIL").build(),
        Airport.builder().name("Bozeman Yellowstone International Airport (was Gallatin Field)").city("Bozeman").state("Montana").iataId("BZN").build(),
        Airport.builder().name("Bert Mooney Airport").city("Butte").state("Montana").iataId("BTM").build(),
        Airport.builder().name("Great Falls International Airport").city("Great Falls").state("Montana").iataId("GTF").build(),
        Airport.builder().name("Helena Regional Airport").city("Helena").state("Montana").iataId("HLN").build(),
        Airport.builder().name("Glacier Park International Airport").city("Kalispell").state("Montana").iataId("GPI").build(),
        Airport.builder().name("Missoula Montana Airport (was Missoula International Airport)").city("Missoula").state("Montana").iataId("MSO").build(),
        Airport.builder().name("Yellowstone Airport").city("West Yellowstone").state("Montana").iataId("WYS").build(),
        Airport.builder().name("Central Nebraska Regional Airport").city("Grand Island").state("Nebraska").iataId("GRI").build(),
        Airport.builder().name("Kearney Regional Airport (was Kearney Municipal)").city("Kearney").state("Nebraska").iataId("EAR").build(),
        Airport.builder().name("Lincoln Airport (was Lincoln Municipal)").city("Lincoln").state("Nebraska").iataId("LNK").build(),
        Airport.builder().name("North Platte Regional Airport (Lee Bird Field)").city("North Platte").state("Nebraska").iataId("LBF").build(),
        Airport.builder().name("Eppley Airfield").city("Omaha").state("Nebraska").iataId("OMA").build(),
        Airport.builder().name("Western Nebraska Regional Airport (William B. Heilig Field)").city("Scottsbluff").state("Nebraska").iataId("BFF").build(),
        Airport.builder().name("Boulder City Municipal Airport").city("Boulder City").state("Nevada").iataId("BVU").build(),
        Airport.builder().name("Elko Regional Airport (J.C. Harris Field)").city("Elko").state("Nevada").iataId("EKO").build(),
        Airport.builder().name("Harry Reid International Airport").city("Las Vegas").state("Nevada").iataId("LAS").build(),
        Airport.builder().name("Reno/Tahoe International Airport").city("Reno").state("Nevada").iataId("RNO").build(),
        Airport.builder().name("Manchester–Boston Regional Airport").city("Manchester").state("New Hampshire").iataId("MHT").build(),
        Airport.builder().name("Portsmouth International Airport at Pease").city("Portsmouth").state("New Hampshire").iataId("PSM").build(),
        Airport.builder().name("Atlantic City International Airport").city("Atlantic City").state("New Jersey").iataId("ACY").build(),
        Airport.builder().name("Newark Liberty International Airport").city("Newark").state("New Jersey").iataId("EWR").build(),
        Airport.builder().name("Trenton Mercer Airport").city("Trenton").state("New Jersey").iataId("TTN").build(),
        Airport.builder().name("Albuquerque International Sunport").city("Albuquerque").state("New Mexico").iataId("ABQ").build(),
        Airport.builder().name("Lea County Regional Airport").city("Hobbs").state("New Mexico").iataId("HOB").build(),
        Airport.builder().name("Roswell Air Center").city("Roswell").state("New Mexico").iataId("ROW").build(),
        Airport.builder().name("Santa Fe Municipal Airport").city("Santa Fe").state("New Mexico").iataId("SAF").build(),
        Airport.builder().name("Albany International Airport").city("Albany").state("New York").iataId("ALB").build(),
        Airport.builder().name("Greater Binghamton Airport (Edwin A. Link Field)").city("Binghamton").state("New York").iataId("BGM").build(),
        Airport.builder().name("Buffalo Niagara International Airport").city("Buffalo").state("New York").iataId("BUF").build(),
        Airport.builder().name("Elmira/Corning Regional Airport").city("Elmira / Corning").state("New York").iataId("ELM").build(),
        Airport.builder().name("Ithaca Tompkins International Airport").city("Ithaca").state("New York").iataId("ITH").build(),
        Airport.builder().name("John F. Kennedy International Airport (was New York International Airport)").city("New York").state("New York").iataId("JFK").build(),
        Airport.builder().name("LaGuardia Airport (and Marine Air Terminal)").city("New York").state("New York").iataId("LGA").build(),
        Airport.builder().name("Long Island MacArthur Airport").city("New York / Islip").state("New York").iataId("ISP").build(),
        Airport.builder().name("New York Stewart International Airport").city("Newburgh").state("New York").iataId("SWF").build(),
        Airport.builder().name("Niagara Falls International Airport").city("Niagara Falls").state("New York").iataId("IAG").build(),
        Airport.builder().name("Ogdensburg International Airport").city("Ogdensburg").state("New York").iataId("OGS").build(),
        Airport.builder().name("Plattsburgh International Airport").city("Plattsburgh").state("New York").iataId("PBG").build(),
        Airport.builder().name("Frederick Douglass/Greater Rochester International Airport").city("Rochester").state("New York").iataId("ROC").build(),
        Airport.builder().name("Syracuse Hancock International Airport").city("Syracuse").state("New York").iataId("SYR").build(),
        Airport.builder().name("Watertown International Airport").city("Watertown").state("New York").iataId("ART").build(),
        Airport.builder().name("Westchester County Airport").city("White Plains").state("New York").iataId("HPN").build(),
        Airport.builder().name("Asheville Regional Airport").city("Asheville").state("North Carolina").iataId("AVL").build(),
        Airport.builder().name("Charlotte Douglas International Airport").city("Charlotte").state("North Carolina").iataId("CLT").build(),
        Airport.builder().name("Concord-Padgett Regional Airport").city("Concord").state("North Carolina").iataId("JQF").build(),
        Airport.builder().name("Fayetteville Regional Airport (Grannis Field)").city("Fayetteville").state("North Carolina").iataId("FAY").build(),
        Airport.builder().name("Piedmont Triad International Airport").city("Greensboro").state("North Carolina").iataId("GSO").build(),
        Airport.builder().name("Pitt–Greenville Airport").city("Greenville").state("North Carolina").iataId("PGV").build(),
        Airport.builder().name("Albert J. Ellis Airport").city("Jacksonville").state("North Carolina").iataId("OAJ").build(),
        Airport.builder().name("Coastal Carolina Regional Airport (was Craven County Regional)").city("New Bern").state("North Carolina").iataId("EWN").build(),
        Airport.builder().name("Raleigh–Durham International Airport").city("Raleigh").state("North Carolina").iataId("RDU").build(),
        Airport.builder().name("Wilmington International Airport").city("Wilmington").state("North Carolina").iataId("ILM").build(),
        Airport.builder().name("Bismarck Municipal Airport").city("Bismarck").state("North Dakota").iataId("BIS").build(),
        Airport.builder().name("Dickinson Theodore Roosevelt Regional Airport").city("Dickinson").state("North Dakota").iataId("DIK").build(),
        Airport.builder().name("Hector International Airport").city("Fargo").state("North Dakota").iataId("FAR").build(),
        Airport.builder().name("Grand Forks International Airport").city("Grand Forks").state("North Dakota").iataId("GFK").build(),
        Airport.builder().name("Jamestown Regional Airport").city("Jamestown").state("North Dakota").iataId("JMS").build(),
        Airport.builder().name("Minot International Airport").city("Minot").state("North Dakota").iataId("MOT").build(),
        Airport.builder().name("Williston Basin International Airport").city("Williston").state("North Dakota").iataId("XWA").build(),
        Airport.builder().name("Akron-Canton Regional Airport").city("Akron / Canton").state("Ohio").iataId("CAK").build(),
        Airport.builder().name("Cleveland Hopkins International Airport").city("Cleveland").state("Ohio").iataId("CLE").build(),
        Airport.builder().name("John Glenn Columbus International Airport").city("Columbus").state("Ohio").iataId("CMH").build(),
        Airport.builder().name("Rickenbacker International Airport").city("Columbus").state("Ohio").iataId("LCK").build(),
        Airport.builder().name("James M. Cox Dayton International Airport").city("Dayton").state("Ohio").iataId("DAY").build(),
        Airport.builder().name("Eugene F. Kranz Toledo Express Airport").city("Toledo").state("Ohio").iataId("TOL").build(),
        Airport.builder().name("Lawton–Fort Sill Regional Airport").city("Lawton").state("Oklahoma").iataId("LAW").build(),
        Airport.builder().name("Will Rogers World Airport").city("Oklahoma City").state("Oklahoma").iataId("OKC").build(),
        Airport.builder().name("Stillwater Regional Airport").city("Stillwater").state("Oklahoma").iataId("SWO").build(),
        Airport.builder().name("Tulsa International Airport").city("Tulsa").state("Oklahoma").iataId("TUL").build(),
        Airport.builder().name("Mahlon Sweet Field").city("Eugene").state("Oregon").iataId("EUG").build(),
        Airport.builder().name("Rogue Valley International–Medford Airport").city("Medford").state("Oregon").iataId("MFR").build(),
        Airport.builder().name("Southwest Oregon Regional Airport (was North Bend Municipal)").city("North Bend").state("Oregon").iataId("OTH").build(),
        Airport.builder().name("Portland International Airport").city("Portland").state("Oregon").iataId("PDX").build(),
        Airport.builder().name("Roberts Field").city("Redmond").state("Oregon").iataId("RDM").build(),
        Airport.builder().name("Lehigh Valley International Airport (was Allentown–Bethlehem–Easton International Airport)").city("Allentown").state("Pennsylvania").iataId("ABE").build(),
        Airport.builder().name("Erie International Airport (Tom Ridge Field)").city("Erie").state("Pennsylvania").iataId("ERI").build(),
        Airport.builder().name("Harrisburg International Airport").city("Harrisburg").state("Pennsylvania").iataId("MDT").build(),
        Airport.builder().name("Arnold Palmer Regional Airport").city("Latrobe").state("Pennsylvania").iataId("LBE").build(),
        Airport.builder().name("Philadelphia International Airport").city("Philadelphia").state("Pennsylvania").iataId("PHL").build(),
        Airport.builder().name("Pittsburgh International Airport").city("Pittsburgh").state("Pennsylvania").iataId("PIT").build(),
        Airport.builder().name("University Park Airport").city("State College").state("Pennsylvania").iataId("UNV").build(),
        Airport.builder().name("Wilkes-Barre/Scranton International Airport").city("Wilkes-Barre / Scranton").state("Pennsylvania").iataId("AVP").build(),
        Airport.builder().name("Block Island State Airport").city("Block Island").state("Rhode Island").iataId("BID").build(),
        Airport.builder().name("Rhode Island T. F. Green International Airport").city("Providence").state("Rhode Island").iataId("PVD").build(),
        Airport.builder().name("Westerly State Airport").city("Westerly").state("Rhode Island").iataId("WST").build(),
        Airport.builder().name("Charleston International Airport / Charleston AFB").city("Charleston").state("South Carolina").iataId("CHS").build(),
        Airport.builder().name("Columbia Metropolitan Airport").city("Columbia").state("South Carolina").iataId("CAE").build(),
        Airport.builder().name("Florence Regional Airport").city("Florence").state("South Carolina").iataId("FLO").build(),
        Airport.builder().name("Greenville–Spartanburg International Airport (Roger Milliken Field)").city("Greenville").state("South Carolina").iataId("GSP").build(),
        Airport.builder().name("Hilton Head Airport").city("Hilton Head").state("South Carolina").iataId("HXD").build(),
        Airport.builder().name("Myrtle Beach International Airport").city("Myrtle Beach").state("South Carolina").iataId("MYR").build(),
        Airport.builder().name("Aberdeen Regional Airport").city("Aberdeen").state("South Dakota").iataId("ABR").build(),
        Airport.builder().name("Pierre Regional Airport").city("Pierre").state("South Dakota").iataId("PIR").build(),
        Airport.builder().name("Rapid City Regional Airport").city("Rapid City").state("South Dakota").iataId("RAP").build(),
        Airport.builder().name("Joe Foss Field").city("Sioux Falls").state("South Dakota").iataId("FSD").build(),
        Airport.builder().name("Watertown Regional Airport").city("Watertown").state("South Dakota").iataId("ATY").build(),
        Airport.builder().name("Lovell Field").city("Chattanooga").state("South Dakota").iataId("CHA").build(),
        Airport.builder().name("McGhee Tyson Airport").city("Knoxville").state("South Dakota").iataId("TYS").build(),
        Airport.builder().name("Memphis International Airport").city("Memphis").state("South Dakota").iataId("MEM").build(),
        Airport.builder().name("Nashville International Airport (Berry Field)").city("Nashville").state("South Dakota").iataId("BNA").build(),
        Airport.builder().name("Tri-Cities Airport").city("Tri-Cities").state("South Dakota").iataId("TRI").build(),
        Airport.builder().name("Abilene Regional Airport").city("Abilene").state("Texas").iataId("ABI").build(),
        Airport.builder().name("Rick Husband Amarillo International Airport").city("Amarillo").state("Texas").iataId("AMA").build(),
        Airport.builder().name("Austin–Bergstrom International Airport").city("Austin").state("Texas").iataId("AUS").build(),
        Airport.builder().name("Jack Brooks Regional Airport (was Southeast Texas Regional)").city("Beaumont").state("Texas").iataId("BPT").build(),
        Airport.builder().name("Brownsville/South Padre Island International Airport").city("Brownsville").state("Texas").iataId("BRO").build(),
        Airport.builder().name("Easterwood Field").city("College Station").state("Texas").iataId("CLL").build(),
        Airport.builder().name("Corpus Christi International Airport").city("Corpus Christi").state("Texas").iataId("CRP").build(),
        Airport.builder().name("Dallas Love Field").city("Dallas").state("Texas").iataId("DAL").build(),
        Airport.builder().name("Dallas Fort Worth International Airport").city("Dallas").state("Texas").iataId("DFW").build(),
        Airport.builder().name("Del Rio International Airport").city("Del Rio").state("Texas").iataId("DRT").build(),
        Airport.builder().name("El Paso International Airport").city("El Paso").state("Texas").iataId("ELP").build(),
        Airport.builder().name("Valley International Airport").city("Harlingen").state("Texas").iataId("HRL").build(),
        Airport.builder().name("George Bush Intercontinental/Houston Airport").city("Houston").state("Texas").iataId("IAH").build(),
        Airport.builder().name("William P. Hobby Airport").city("Houston").state("Texas").iataId("HOU").build(),
        Airport.builder().name("Killeen–Fort Hood Regional Airport / Robert Gray Army Airfield").city("Killeen").state("Texas").iataId("GRK").build(),
        Airport.builder().name("Laredo International Airport").city("Laredo").state("Texas").iataId("LRD").build(),
        Airport.builder().name("East Texas Regional Airport").city("Longview").state("Texas").iataId("GGG").build(),
        Airport.builder().name("Lubbock Preston Smith International Airport").city("Lubbock").state("Texas").iataId("LBB").build(),
        Airport.builder().name("McAllen Miller International Airport").city("McAllen").state("Texas").iataId("MFE").build(),
        Airport.builder().name("Midland International Air and Space Port").city("Midland / Odessa").state("Texas").iataId("MAF").build(),
        Airport.builder().name("San Angelo Regional Airport (Mathis Field)").city("San Angelo").state("Texas").iataId("SJT").build(),
        Airport.builder().name("San Antonio International Airport").city("San Antonio").state("Texas").iataId("SAT").build(),
        Airport.builder().name("Tyler Pounds Regional Airport").city("Tyler").state("Texas").iataId("TYR").build(),
        Airport.builder().name("Waco Regional Airport").city("Waco").state("Texas").iataId("ACT").build(),
        Airport.builder().name("Wichita Falls Municipal Airport / Sheppard Air Force Base").city("Wichita Falls").state("Texas").iataId("SPS").build(),
        Airport.builder().name("Cedar City Regional Airport").city("Cedar City").state("Utah").iataId("CDC").build(),
        Airport.builder().name("Canyonlands Regional Airport").city("Moab").state("Utah").iataId("CNY").build(),
        Airport.builder().name("Ogden-Hinckley Airport").city("Ogden").state("Utah").iataId("OGD").build(),
        Airport.builder().name("Provo Municipal Airport").city("Provo").state("Utah").iataId("PVU").build(),
        Airport.builder().name("St. George Regional Airport").city("St. George").state("Utah").iataId("SGU").build(),
        Airport.builder().name("Salt Lake City International Airport").city("Salt Lake City").state("Utah").iataId("SLC").build(),
        Airport.builder().name("Burlington International Airport").city("Burlington").state("Vermont").iataId("BTV").build(),
        Airport.builder().name("Charlottesville–Albemarle Airport").city("Charlottesville").state("Virginia").iataId("CHO").build(),
        Airport.builder().name("Lynchburg Regional Airport (Preston Glenn Field)").city("Lynchburg").state("Virginia").iataId("LYH").build(),
        Airport.builder().name("Newport News/Williamsburg International Airport (Patrick Henry Field)").city("Newport News").state("Virginia").iataId("PHF").build(),
        Airport.builder().name("Norfolk International Airport").city("Norfolk").state("Virginia").iataId("ORF").build(),
        Airport.builder().name("Richmond International Airport (Byrd Field)").city("Richmond").state("Virginia").iataId("RIC").build(),
        Airport.builder().name("Roanoke–Blacksburg Regional Airport (Woodrum Field)").city("Roanoke").state("Virginia").iataId("ROA").build(),
        Airport.builder().name("Shenandoah Valley Regional Airport").city("Staunton / Waynesboro / Harrisonburg").state("Virginia").iataId("SHD").build(),
        Airport.builder().name("Ronald Reagan Washington National Airport").city("Washington, D.C. / Arlington").state("Virginia").iataId("DCA").build(),
        Airport.builder().name("Washington Dulles International Airport").city("Washington, D.C. / Dulles / Chantilly").state("Virginia").iataId("IAD").build(),
        Airport.builder().name("Bellingham International Airport").city("Bellingham").state("Washington").iataId("BLI").build(),
        Airport.builder().name("Orcas Island Airport").city("Eastsound").state("Washington").iataId("ORS").build(),
        Airport.builder().name("Paine Field (Snohomish County Airport)").city("Everett").state("Washington").iataId("PAE").build(),
        Airport.builder().name("Friday Harbor Airport").city("Friday Harbor").state("Washington").iataId("FHR").build(),
        Airport.builder().name("Tri-Cities Airport").city("Pasco").state("Washington").iataId("PSC").build(),
        Airport.builder().name("Pullman–Moscow Regional Airport").city("Pullman / Moscow, Idaho").state("Washington").iataId("PUW").build(),
        Airport.builder().name("King County International Airport (Boeing Field)").city("Seattle").state("Washington").iataId("BFI").build(),
        Airport.builder().name("Seattle–Tacoma International Airport").city("Seattle / Tacoma (SeaTac)").state("Washington").iataId("SEA").build(),
        Airport.builder().name("Spokane International Airport (Geiger Field)").city("Spokane").state("Washington").iataId("GEG").build(),
        Airport.builder().name("Walla Walla Regional Airport").city("Walla Walla").state("Washington").iataId("ALW").build(),
        Airport.builder().name("Pangborn Memorial Airport").city("Wenatchee").state("Washington").iataId("EAT").build(),
        Airport.builder().name("Yakima Air Terminal (McAllister Field)").city("Yakima").state("Washington").iataId("YKM").build(),
        Airport.builder().name("Yeager Airport").city("Charleston").state("West Virginia").iataId("CRW").build(),
        Airport.builder().name("North Central West Virginia Airport (was Harrison-Marion Regional)").city("Clarksburg").state("West Virginia").iataId("CKB").build(),
        Airport.builder().name("Tri-State Airport (Milton J. Ferguson Field)").city("Huntington").state("West Virginia").iataId("HTS").build(),
        Airport.builder().name("Greenbrier Valley Airport").city("Lewisburg").state("West Virginia").iataId("LWB").build(),
        Airport.builder().name("Appleton International Airport").city("Appleton").state("Wisconsin").iataId("ATW").build(),
        Airport.builder().name("Chippewa Valley Regional Airport").city("Eau Claire").state("Wisconsin").iataId("EAU").build(),
        Airport.builder().name("Green Bay–Austin Straubel International Airport").city("Green Bay").state("Wisconsin").iataId("GRB").build(),
        Airport.builder().name("La Crosse Regional Airport").city("La Crosse").state("Wisconsin").iataId("LSE").build(),
        Airport.builder().name("Dane County Regional Airport (Truax Field)").city("Madison").state("Wisconsin").iataId("MSN").build(),
        Airport.builder().name("Milwaukee Mitchell International Airport").city("Milwaukee").state("Wisconsin").iataId("MKE").build(),
        Airport.builder().name("Central Wisconsin Airport").city("Mosinee").state("Wisconsin").iataId("CWA").build(),
        Airport.builder().name("Rhinelander–Oneida County Airport").city("Rhinelander").state("Wisconsin").iataId("RHI").build(),
        Airport.builder().name("Casper–Natrona County International Airport").city("Casper").state("Wyoming").iataId("CPR").build(),
        Airport.builder().name("Yellowstone Regional Airport").city("Cody").state("Wyoming").iataId("COD").build(),
        Airport.builder().name("Gillette–Campbell County Airport").city("Gillette").state("Wyoming").iataId("GCC").build(),
        Airport.builder().name("Jackson Hole Airport").city("Jackson").state("Wyoming").iataId("JAC").build(),
        Airport.builder().name("Laramie Regional Airport").city("Laramie").state("Wyoming").iataId("LAR").build(),
        Airport.builder().name("Central Wyoming Regional Airport (was Riverton Regional)").city("Riverton").state("Wyoming").iataId("RIW").build(),
        Airport.builder().name("Southwest Wyoming Regional Airport (Rock Springs–Sweetwater County Airport)").city("Rock Springs").state("Wyoming").iataId("RKS").build(),
        Airport.builder().name("Sheridan County Airport").city("Sheridan").state("Wyoming").iataId("SHR").build(),
        Airport.builder().name("Antonio B. Won Pat International Airport").city("Agana / Tamuning").state("Guam").iataId("GUM").build(),
        Airport.builder().name("Saipan International Airport (Francisco C. Ada)").city("Obyan, Saipan Island").state("Northern Marianas").iataId("GSN").build(),
        Airport.builder().name("Tinian International Airport (West Tinian)").city("Tinian Island").state("Northern Marianas").iataId("TNI").build(),
        Airport.builder().name("Rafael Hernández Airport").city("Aguadilla").state("Puerto Rico").iataId("BQN").build(),
        Airport.builder().name("José Aponte de la Torre Airport").city("Ceiba").state("Puerto Rico").iataId("RVR").build(),
        Airport.builder().name("Benjamín Rivera Noriega Airport").city("Culebra").state("Puerto Rico").iataId("CPX").build(),
        Airport.builder().name("Mercedita Airport").city("Ponce").state("Puerto Rico").iataId("PSE").build(),
        Airport.builder().name("Fernando Luis Ribas Dominicci Airport (Isla Grande Airport)").city("San Juan").state("Puerto Rico").iataId("SIG").build(),
        Airport.builder().name("Luis Muñoz Marín International Airport").city("San Juan / Carolina").state("Puerto Rico").iataId("SJU").build(),
        Airport.builder().name("Antonio Rivera Rodríguez Airport").city("Vieques").state("Puerto Rico").iataId("VQS").build(),
        Airport.builder().name("Cyril E. King Airport").city("Charlotte Amalie, St. Thomas").state("U.S. Virgin Islands").iataId("STT").build(),
        Airport.builder().name("Henry E. Rohlsen Airport").city("Christiansted, St. Croix").state("U.S. Virgin Islands").iataId("STX").build());
}
